### ISSUE TITLE
HTTP Exception 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by sal0max** [narorolib/fer#2]
Hi,

I'm using this API as an option in my app https://github.com/sal0max/currencies.
Everything works fine in the app. There's just one thing.

I'm running jUnit tests to check if each of the endpoints is still up and responding.
I test both `/latest` and timeline (e. g. `/2010-01-01..2010-01-31`) endpoints.

Locally, the test succeeds. However, when run as GitHub Action, the test fails with following stack trace:

```
de.salomax.currencies.repository.ExchangeRatesServiceTest > testFerEe FAILED
    HTTP Exception 503 Service Temporarily Unavailable
    	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
    	com.github.kittinunf.fuel.core.DeserializableKt$serializeFor$2.invoke(Deserializable.kt:288)
    	com.github.kittinunf.fuel.core.DeserializableKt$serializeFor$2.invoke(Deserializable.kt)
    	com.github.kittinunf.result.ResultKt.mapError(Result.kt:51)
    	com.github.kittinunf.fuel.core.DeserializableKt.serializeFor(Deserializable.kt:287)
    	com.github.kittinunf.fuel.core.DeserializableKt.awaitResult(Deserializable.kt:268)
    	de.salomax.currencies.repository.ExchangeRatesService.getRates(ExchangeRatesService.kt:44)
    	de.salomax.currencies.repository.ExchangeRatesServiceTest$testFerEe$1.invokeSuspend(ExchangeRatesServiceTest.kt:47)
    	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
...
```

This HTTP 503 only happens with this endpoint. The exact same test succeeds when run against https://api.exchangerate.host and https://api.frankfurter.app.

Any idea what's happening here? 503 is a server, not a client error.

Let me know if you need more information.

**Comment by emperorjoker** [comment]
Does this problem always occur when you use GitHub Action or only occur occasionally?

If it only happens occasionally, can you give me the timestamp?

**Comment by sal0max** [comment]
Ever since I added this unit test, it is always failing because of it.
Last time the Action ran and failed, was Fri, 24 Sep 2021 23:27:52 GMT.

**Comment by emperorjoker** [comment]
We suspect that this problem is caused by the limitation of the number of requests.

Therefore, we have adjusted the web server settings earlier today, and hope this will improve the issue you are experiencing.

Please let me know if you run into this issue again.

**Comment by sal0max** [comment]
Thanks a lot for looking into this!

I just re-ran the job and still got the same error message:
Thu, 30 Sep 2021 14:39:06 GMT

**Comment by emperorjoker** [comment]
Thank you for your feedback, it helps us so much. 

We have clarified what the problem is.

We just turned off the corresponding rules of Cloudflare Firewall, and now there should be no problem.

**Comment by sal0max** [comment]
Wow, I'm impressed!

Re-ran the task again (API call @ ~Thu, 30 Sep 2021 15:04:03 GMT) and it was a success.

Thanks so much for your webservice and for the great support 👍!
