### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by azeteg** [narorolib/fer#5]
The API is completely down since about a week, only getting me to a Cloudflare 502 page.

**Comment by sal0max** [comment]
Yep, 502 for me, too.

**Comment by emperorjoker** [comment]
@azeteg @sal0max I apologize for the delay in my response.

This is caused by a port conflict due to migration to a new server. 

Service has now been restored.

**Comment by sal0max** [comment]
Great! Thanks a lot @emperorjoker
