### ISSUE TITLE
HTTP Exception 422 Unprocessable Entity

### ISSUE THREAD

**Issue by sal0max** [narorolib/fer#6]
Hi,

at least since yesterday (Feb 2, 2024, 2:28 AM GMT+1), the API _most of the time_ returns `HTTP Exception 422 Unprocessable Entity`.

I noticed, because my unit tests are failing: https://github.com/sal0max/currencies/actions

- The error occurs via GitHub Actions, but also locally in my dev environment.
- It happens most of the time, but not always. I just made 20 calls in one minute: 16 failed.
- Test calls are
   - https://api.fer.ee/latest?base=EUR
   - https://api.fer.ee/2023-02-03..2024-02-03?base=EUR&symbols=ISK

**Comment by emperorjoker** [comment]
Thanks. Service has been restored. The database service provider has changed their URL rules, rendering the service inaccessible.
